name: LoginSystem
version: 1.0.0
main: BlawoHD\LoginSystem
api: 1.14.0
website: https://BlawoHDNetwork.jimdo.com/
commands:
    register:
        description: Register Command
        aliases: [reg, r]
    login:
        description: Login Command
        aliases: [log, l]
